Instructor.create!([
  {name: "Maggie Moss", position: "Web Developer", description: "The curriculum for this course was created by Maggie Moss. Maggie was part of our rockstar January cohort in Vancouver, and now she's passing on that knowledge to our students in as the instructor for our Intro to Web Development course in Toronto. She currently works as a Rails developer @ShopStorm."},
  {name: "David VanDusen", position: "Web Developer & Instructor", description: "David is a sort of web dev Don Quixote, helping out wherever he is needed. He has grappled with his share of technological windmills yet continues his chivalrous fight for clean, beautiful code. That said, David is a renaissance man and pursues fine arts and music in his leisure."},
  {name: "Juan Gonzalez", position: "Web Developer & Instructor", description: "Juan is a Software Engineer who allegedly sold his first project in 1988. Whatever language was used to develop it has been forgotten. More recently he has been an entrepreneur with a passion for all things video."},
  {name: "David Mills", position: "iOS Developer", description: "David Mills has been working as a Web and Mobile developer for the last 7 years. In that time he's worked for a Digital Agency, where he helped build, test and launch websites for brands such as Adidas, Sleeman and McCain. While at the agency he taught himself iOS development, and moved into the startup space, looking for a new challenge, working for a variety of startups building iOS and Web applications. Looking for his next challenge, he currently teaches with Lighthouse Labs, leading lectures and mentoring both the Web and iOS bootcamps in Toronto."}
])
Course.create!([
  {name: "HTML & CSS Essentials", coursename: "html-css-essentials", blurb: "Learn to build basic web pages using HTML & CSS.", description: "This course was created by Lighthouse Labs to introduce you to the basics of coding. This is just the beginning - there is a world of resources and avenues available for you to grow your digital literacy. Learning to code is more accessible than ever, whether it's learning in person, online or a little bit of both, there are endless ways you can expand your knowledge.", instructor_id: 1},
  {name: "JavaScript Essentials", coursename: "js-essentials", blurb: "Learn to build and style your own web-based chat app using JavaScript.", description: "In this free course, you'll be learning how to build your own web-based chat app similar to Twitch or Slack using JavaScript and other modern tools like Node.js and Web Sockets. The goal of this course is to introduce you to the fundamentals of building web-based applications using some of the most prominent and widely used programming technologies!\n\nIf you're new to programming, we recommend you start with our HTML & CSS Essentials course.", instructor_id: 2},
  {name: "JavaScript Essentials Part II", coursename: "js-essentials-2", blurb: "Upgrade your chat app by building your own Bot with JavaScript.", description: "This course will be building on our JavaScript Essentials Part I course, where we created a web-based chat app. Our focus today will be to make this chat app much smarter by adding some super powers, very much the way that Messenger or Slack or many other conversational interfaces are becoming smarter: with a BOT.", instructor_id: 3},
  {name: "iOS Essentials", coursename: "ios-essentials", blurb: "Learn the basics of iOS development using Swift by building a mobile music player.", description: "In this free course, you'll be learning how to build your own music player similar to your iTunes or Spotify app using Apple's popular programming language Swift. The goal of this course is to introduce you to the fundamentals of building mobile applications using some of the most prominent and widely used programming technologies!\n\nIf you're new to programming, we recommend you start with our HTML & CSS Essentials course.", instructor_id: 4}
])
Chapter.create!([
  {name: "Welcome!", chapter_number: 1, course_id: 3},
  {name: "Building A Bot", chapter_number: 2, course_id: 3},
  {name: "Fetching Data From APIs", chapter_number: 3, course_id: 3},
  {name: "Continue Your Learning", chapter_number: 4, course_id: 3},
  {name: "Welcome!", chapter_number: 1, course_id: 1},
  {name: "Intro to HTML", chapter_number: 2, course_id: 1},
  {name: "Intro to CSS", chapter_number: 3, course_id: 1},
  {name: "Practice Your Skills", chapter_number: 4, course_id: 1},
  {name: "Keep Learning!", chapter_number: 5, course_id: 1},
  {name: "Welcome!", chapter_number: 1, course_id: 2},
  {name: "Styling With HTML & CSS", chapter_number: 2, course_id: 2},
  {name: "Functionality With JavaScript", chapter_number: 3, course_id: 2},
  {name: "Continue Your Learning", chapter_number: 4, course_id: 2},
  {name: "Welcome", chapter_number: 1, course_id: 4}
])
Section.create!([
  {name: "Introduction", sectionname: "intro", section_number: 1, content: "### Welcome to Part II of our JavaScript Essentials course!\n\nThis curriculum was created by the Lighthouse Labs education team for our free JavaScript Essentials Workshops. Our goal is to show you how modern web applications are built by bringing together software components that may be located elsewhere but that can be combined to create more complex behaviour. To do so, we'll learn how Javascript provides all the essential tools to GET data from other sources and manipulate that data to fit our needs.\n\n### You will have needed to completed JavaScript Essentials Part I in order to continue with this course.\n\n### Who are we?\n\nWe're Lighthouse Labs (👋 ), a Canadian software development school aiming to change the way tech education is being delivered. Our goal is to find the best ways to train the next generation of developers and to empower everyone to take ownership over their digital literacy.\n\n### How do we do that?\n\nWe offer in-person courses in web or iOS development in seven Canadian cities, with a ton of hands-on experience and access to mentorship from seasoned Developers in your community. Our courses provide people with data-driven curriculum covering modern languages and frameworks that are essential for those working in the technology industry.\n\n### Web or iOS Development Bootcamp - 8 weeks, full-time immersive (500+ hours)\n\nThe goal of our Bootcamps is to transform you into a professional Developer. You’ll come to understand coding logic using popular languages and frameworks, while learning how to think like a programmer by building software from the ground up. Bootcamp will provide you with mentorship, data-driven curriculum, and a top notch learning environment that will launch you into your first Junior Developer role with an over 96% employment rate for job seeking graduates.\n\n### Intro to Web or iOS Development - 6 weeks, part-time twice a week (36+ hours)\n\nThis course is focused on equipping you with tools that apply directly to professional web or iOS development. You'll learn what goes in to creating and deploying apps and will gain a solid understanding of the fundamentals of programming. This course is an excellent option for anyone looking to discover if they want to become a Developer, to learn to communicate with a dev team or to gain valuable coding experience for a hybrid technical role.\n\n🚀 In addition to our courses, we often host free workshops and events geared towards new coders. Click here to find the next event near you! You can also get in touch to book a tour of our campus or take a virtual tour below.\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/jpV63pXI5d0\" frameborder=\"0\" allow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\n", chapter_id: 1},
  {name: "Building A Chat Bot", sectionname: "building-a-chat-bot", section_number: 2, content: "### PRE-REQ\n\nIf you are thinking about taking this course, you've probably attended Part I where we built a simple chat application using modern web tools such as Node.js, Websockets and JQuery.  If you didn't, please note that we'll start exactly where we left off.", chapter_id: 1},
  {name: "Getting Started", sectionname: "getting-started", section_number: 3, content: "### CLONE \n\n![Screenshot](/js2-screenshot.png)", chapter_id: 1},
  {name: "Code Review", sectionname: "code-review", section_number: 1, content: "### CODE REVIEW\n\n", chapter_id: 2},
  {name: "Conversational Bots", sectionname: "conversational-bots", section_number: 2, content: "### CONVERSATIONAL BOTS\n\n <iframe height=\"265\" scrolling=\"no\" src=\"//codepen.io/nullobject/embed/rAbio/?height=265&theme-id=0&default-tab=js,result&embed-version=2\" frameborder=\"no\" allowtransparency=\"true\" allowfullscreen style=\"width: 100%;\">See the Pen <a href=\"https://codepen.io/nullobject/pen/rAbio/\">CodePen JavaScript Console Template</a> by Josh Bassett (<a href=\"https://codepen.io/nullobject\">@nullobject</a>) on <a href=\"https://codepen.io\">CodePen</a>.</iframe>\n", chapter_id: 2},
  {name: "What Are APIs?", sectionname: "what-are-apis", section_number: 1, content: "### APIS\n\n", chapter_id: 3},
  {name: "Interacting with APIs", sectionname: "interacting-with-apis", section_number: 2, content: "### CURL \n\n", chapter_id: 3},
  {name: "GET Requests", sectionname: "get-requests", section_number: 3, content: "### GET\n\n", chapter_id: 3},
  {name: "Callbacks", sectionname: "callbacks", section_number: 4, content: "### CALLBACKS \n\n", chapter_id: 3},
  {name: "Wrap-Up", sectionname: "wrap-up", section_number: 5, content: "### WRAP-UP\n\nIf you are following step by step, you should be able to ask for the weather in your chat room.  Remember to ask nicely by ending with a question mark (?).  Otherwise now is a good time to catch up by looking at the full version of the code and comparing against your own.  \n\nBetween Regular Expressions, JSON and Callbacks, we did cover quite a bit of ground on our server-side javascript skills, so do not worry if you are still munching over some of the concepts.  Keep asking questions.  ", chapter_id: 3},
  {name: "Lighthouse Labs Prep Course", sectionname: "lighthouse-labs-prep-course", section_number: 1, content: "### Lighthouse Labs Prep Course 🏋🏽\n\nAll incoming students for the Lighthouse Labs Web Development Bootcamp and iOS Development Bootcamp are required to complete 40-60 hours or preparatory work before they enter the classroom. Our prep course covers the foundation that is necessary for students to hit the ground running on day one! The prep material consists of some of our favourite resources paired with curriculum created by the Lighthouse Labs education team.\n\nWeb Development Bootcamp Prep Course | iOS Development Bootcamp Prep Course\n\nIf you're looking to dive deeper into Web or iOS Development or get a better idea of what taking our Bootcamp will entail, this is a great place to start.\n\n", chapter_id: 4},
  {name: "Additional Resources", sectionname: "additional-resources", section_number: 2, content: "### Additional Resources 📕\n\nLearning to code is more accessible than ever! There are endless online resources that cater to every learning style, and local organizations that offer free workshops for you to learn in person. If you're looking for more ways to explore programming or are getting stuck in a coding rut, explore some of the recommendations below or read our guide on How To Learn To Code.\n\n\n### Online Resources\n\nBento\n\nCodecademy\n\nCoderByte\n\nCodeWars\n\nEloquent JavaScript\n\nKhanAcademy\n\nTreehouse\n\n\n### Coding Non-Profits & Community Groups\n\nApp Camp For Girls\n\nBridging To Technology\n\nKids Code Jeunesse\n\nLadies Learning Code\n\nLighthouse Labs Workshops\n\n\n\n### Books/Videos\n\nHow To Learn To Code\n\nLearn Code The Hard Way", chapter_id: 4},
  {name: "Introduction", sectionname: "intro", section_number: 1, content: "### Intro", chapter_id: 5},
  {name: "Who Are We?", sectionname: "who-are-we", section_number: 2, content: "### Who Are We", chapter_id: 5},
  {name: "What Can We Create?", sectionname: "what-can-we-create", section_number: 3, content: "### What Can We Create?", chapter_id: 5},
  {name: "Get Started", sectionname: "get-started", section_number: 4, content: "### Get Started", chapter_id: 5},
  {name: "HTML", sectionname: "html", section_number: 1, content: "### HTML", chapter_id: 6},
  {name: "Image Tags", sectionname: "image-tags", section_number: 2, content: "### Image Tags", chapter_id: 6},
  {name: "Text Tags", sectionname: "text-tags", section_number: 3, content: "### Text Tags", chapter_id: 6},
  {name: "Creating Lists", sectionname: "creating-lists", section_number: 4, content: "### Creating Lists", chapter_id: 6},
  {name: "Creating Links", sectionname: "creating-links", section_number: 5, content: "### Creating Links", chapter_id: 6},
  {name: "Structuring Your Pages", sectionname: "structuring-your-pages", section_number: 6, content: "### Structuring Your Pages", chapter_id: 6},
  {name: "Debugging", sectionname: "debugging", section_number: 7, content: "### Debugging", chapter_id: 6},
  {name: "Cascading Style Sheets", sectionname: "cascading-style-sheets", section_number: 1, content: "### Cascading Style Sheets", chapter_id: 7},
  {name: "Selectors, Classes & IDs", sectionname: "selectors-classes-ids", section_number: 2, content: "### Selectors, Classes & IDs", chapter_id: 7},
  {name: "Fonts", sectionname: "fonts", section_number: 3, content: "### Fonts", chapter_id: 7},
  {name: "Colours", sectionname: "colours", section_number: 4, content: "### Colours", chapter_id: 7},
  {name: "Margins & Padding", sectionname: "margins-padding", section_number: 5, content: "### Margins & Padding", chapter_id: 7},
  {name: "Specificity", sectionname: "specificity", section_number: 6, content: "### Specificity", chapter_id: 7},
  {name: "Positioning", sectionname: "positioning", section_number: 7, content: "### Positioning", chapter_id: 7},
  {name: "Debugging", sectionname: "debugging", section_number: 8, content: "### Debugging", chapter_id: 7},
  {name: "Tutorial: Building A Webpage", sectionname: "tutorial-building-a-webpage", section_number: 1, content: "### Tutorial: Building A Webpage", chapter_id: 8},
  {name: "Words Of Wis-Don", sectionname: "words-of-wis-don", section_number: 2, content: "### Words Of Wis-Don", chapter_id: 8},
  {name: "Lighthouse Labs Prep Course", sectionname: "lighthouse-labs-prep-course", section_number: 1, content: "### Lighthouse Labs Prep Course", chapter_id: 9},
  {name: "Additional Resources", sectionname: "additional-resources", section_number: 2, content: "### Additional Resources", chapter_id: 9},
  {name: "Introduction", sectionname: "intro", section_number: 1, content: "### Intro", chapter_id: 10},
  {name: "What Is JavaScript?", sectionname: "what-is-javascript", section_number: 2, content: "### What Is JavaScript?", chapter_id: 10},
  {name: "Building A Chat App", sectionname: "building-a-chat-app", section_number: 3, content: "### Building A Chat App", chapter_id: 10},
  {name: "Setup", sectionname: "set-up", section_number: 4, content: "### Setup", chapter_id: 10},
  {name: "HTML", sectionname: "html", section_number: 1, content: "### HTML", chapter_id: 11},
  {name: "CSS", sectionname: "css", section_number: 2, content: "### CSS", chapter_id: 11},
  {name: "Example CSS", sectionname: "example-css", section_number: 3, content: "### Example CSS", chapter_id: 11},
  {name: "Client Side", sectionname: "client-side", section_number: 1, content: "### Client Side", chapter_id: 12},
  {name: "Node", sectionname: "node", section_number: 2, content: "### Node", chapter_id: 12},
  {name: "Express", sectionname: "express", section_number: 3, content: "### Express", chapter_id: 12},
  {name: "Socket.io", sectionname: "socket-io", section_number: 4, content: "### Socket.io", chapter_id: 12},
  {name: "Enhancements (Stretch Goals!)", sectionname: "enhancements", section_number: 5, content: "### Enhancements (Stretch Goals!)", chapter_id: 12},
  {name: "Lighthouse Labs Prep Course", sectionname: "lighthouse-labs-prep-course", section_number: 1, content: "### Lighthouse Labs Prep Course", chapter_id: 13},
  {name: "Additional Resources", sectionname: "additional-resources", section_number: 2, content: "### Additional Resources", chapter_id: 13},
  {name: "Intro", sectionname: "intro", section_number: 1, content: "### Intro", chapter_id: 14}
])
User.create!([
  {first_name: "Jack", last_name: "Black", location: "Vancouver", motivation: "coding sounded fun", email: "jack@black.com", password: "longunreadablestring", password_confirmation: "longunreadablestring"},
  {first_name: "Rosalind", last_name: "Lake", location: "Toronto", motivation: "I'd like to build my own webpage", email: "rosy@lake.com", password: "yepyepyep", password_confirmation: "yepyepyep"},
  {first_name: "Connie", last_name: "Choi", location: "Vancouver", motivation: "I'd like to build my own webpage", email: "connie@connie.com", password: "connieconnie", password_confirmation: "connieconnie"}

])
Review.create!([
  {rating: 5, review: "Wow, look what I can do! It was so much fun to build on the first JS course.", show_flag: true, course_id: 3, user_id: 1},
  {rating: 5, review: "I was pleasantly surprised at how much I was able to learn in such a relatively short period of time.", show_flag: true, course_id: 3, user_id: 2},
  {rating: 5, review: "Neat-o!", show_flag: true, course_id: 1, user_id: 1},
  {rating: 5, review: "I really enjoyed getting a taste of JavaScript. This course made it fun!", show_flag: true, course_id: 2, user_id: 2},
  {rating: 5, review: "Woohoo! I can build an app!", show_flag: true, course_id: 4, user_id: 1}
])
UserSection.create!([
  {section_id: 1, user_id: 1},
  {section_id: 2, user_id: 1},
  {section_id: 3, user_id: 1},
  {section_id: 4, user_id: 1},
  {section_id: 5, user_id: 1},
  {section_id: 6, user_id: 1},
  {section_id: 7, user_id: 1},
  {section_id: 8, user_id: 1},
  {section_id: 9, user_id: 1},
  {section_id: 10, user_id: 1},
  {section_id: 11, user_id: 1},
  {section_id: 12, user_id: 1},
  {section_id: 1, user_id: 2},
  {section_id: 2, user_id: 2},
  {section_id: 3, user_id: 2},
  {section_id: 4, user_id: 2},
  {section_id: 5, user_id: 2},
  {section_id: 1, user_id: 3},
  {section_id: 2, user_id: 3},
  {section_id: 3, user_id: 3},
  {section_id: 4, user_id: 3},
  {section_id: 13, user_id: 3},
  {section_id: 14, user_id: 3},
  {section_id: 15, user_id: 3},
  {section_id: 16, user_id: 3},
  {section_id: 17, user_id: 3},
  {section_id: 18, user_id: 3},
  {section_id: 19, user_id: 3},
  {section_id: 20, user_id: 3},
  {section_id: 21, user_id: 3},
  {section_id: 22, user_id: 3},
  {section_id: 23, user_id: 3},
  {section_id: 24, user_id: 3},
  {section_id: 25, user_id: 3},
  {section_id: 26, user_id: 3},
  {section_id: 27, user_id: 3},
  {section_id: 28, user_id: 3},
  {section_id: 29, user_id: 3},
  {section_id: 30, user_id: 3},
  {section_id: 31, user_id: 3},
  {section_id: 32, user_id: 3},
  {section_id: 33, user_id: 3},
  {section_id: 34, user_id: 3},
  {section_id: 35, user_id: 3},
  {section_id: 36, user_id: 3},
  {section_id: 37, user_id: 3},
  {section_id: 38, user_id: 3},
  {section_id: 39, user_id: 3},
  {section_id: 40, user_id: 3},
  {section_id: 41, user_id: 3},
  {section_id: 42, user_id: 3},
  {section_id: 43, user_id: 3},
  {section_id: 44, user_id: 3},
  {section_id: 45, user_id: 3},
  {section_id: 46, user_id: 3},
  {section_id: 47, user_id: 3},
  {section_id: 48, user_id: 3},
  {section_id: 49, user_id: 3}
])
